export const PATHS = Object.freeze({
  landing: '/',
  favoriteHome: '/favorite-home',
  survey: '/survey',
  surveyResume: '/survey/:surveyId',
  recommendedProperty: '/recommend',
  propertyDetail: '/recommend/:homeId',
  evaluationMethod: '/evaluation-method',
  login: '/login',
  emailLogin: '/login/email',
  signup: '/signup',
  emailVerification: '/auth/email/verify',
  passwordResetRequest: '/password/reset/request',
  passwordReset: '/auth/password/reset',
  socialCallback: '/auth/social/callback',
  profile: '/me',
  socialProfile: '/social/profile',
  legacyMain: '/main',
  legacyRecommendedProperty: '/process/recommended',
})
