export const PATHS = Object.freeze({
  landing: '/',
  favoriteHome: '/favorite-home',
  surveyProcess: '/process/survey',
  recommendedProperty: '/process/recommended',
  evaluationMethod: '/evaluation-method',
  login: '/login',
  emailLogin: '/login/email',
  signup: '/signup',
  emailVerification: '/auth/email/verify',
  passwordResetRequest: '/password/reset/request',
  passwordReset: '/auth/password/reset',
  socialCallback: '/auth/social/callback',
  profile: '/me',
  socialProfile: '/social/profile',
  survey: '/main',
})
