import { PATHS } from '../paths'

export const routes = [
  { path: PATHS.landing, component: () => import('@/views/landing/LandingView.vue') },
  { path: PATHS.favoriteHome, component: () => import('@/views/favorite/MainView.vue'), meta: { requiresAuth: true, process: true } },
  { path: PATHS.survey, name: 'survey', component: () => import('@/views/survey/SurveyView.vue'), meta: { requiresAuth: true, process: true } },
  { path: PATHS.surveyResume, name: 'survey-resume', component: () => import('@/views/survey/SurveyView.vue'), props: true, meta: { requiresAuth: true, process: true } },
  { path: PATHS.recommendedProperty, name: 'recommend-list', component: () => import('@/views/house/RecommendationList.vue'), meta: { requiresAuth: true, process: true } },
  { path: PATHS.propertyDetail, name: 'property-detail', component: () => import('@/views/house/PropertyDetail.vue'), props: true, meta: { requiresAuth: true } },
  { path: PATHS.legacyMain, redirect: PATHS.survey },
  { path: PATHS.legacyRecommendedProperty, redirect: PATHS.recommendedProperty },
  { path: PATHS.evaluationMethod, component: () => import('@/views/favorite/EvaluationMethodView.vue'), meta: { requiresAuth: true } },
  { path: PATHS.login, component: () => import('@/views/auth/LoginChoiceView.vue') },
  { path: PATHS.emailLogin, component: () => import('@/views/auth/EmailLoginView.vue') },
  { path: PATHS.signup, component: () => import('@/views/auth/SignupView.vue') },
  { path: PATHS.emailVerification, component: () => import('@/views/auth/EmailVerificationResultView.vue') },
  { path: PATHS.passwordResetRequest, component: () => import('@/views/auth/PasswordResetRequestView.vue') },
  { path: PATHS.passwordReset, component: () => import('@/views/auth/PasswordResetCompleteView.vue') },
  { path: PATHS.socialCallback, component: () => import('@/views/auth/SocialLoginCallbackView.vue') },
  { path: PATHS.profile, component: () => import('@/views/account/ProfileView.vue'), meta: { requiresAuth: true } },
  { path: PATHS.socialProfile, component: () => import('@/views/auth/SocialProfileCompletionView.vue') },
  { path: PATHS.financeHorizon, name: 'finance-horizon', component: () => import('@/views/finance/HorizonScenarioView.vue'), meta: { requiresAuth: true, process: true } },
  { path: PATHS.financeRecommendation, name: 'recommendation', component: () => import('@/views/RecommendationConditionView.vue'), meta: { requiresAuth: true, process: true } },
  { path: PATHS.financeRecommendationResult, name: 'recommendation-result', component: () => import('@/views/RecommendationResultView.vue'), meta: { requiresAuth: true, process: false } },
  { path: PATHS.financeRecommendationFavorites, name: 'recommendation-favorites', component: () => import('@/views/RecommendationFavoritesView.vue'), meta: { requiresAuth: true, process: true } },
  { path: PATHS.financeProductDetail, name: 'product-detail', component: () => import('@/views/ProductDetailView.vue'), props: true },
  { path: PATHS.summary, name: 'summary', component: () => import('@/views/summary/SummaryView.vue'), meta: { requiresAuth: true, process: true } },
]
